### ISSUE TITLE
Keys have expired

### ISSUE THREAD

**Issue by shvchk** [netbirdio/public-keys#1]
When doing `apt update` I get the following error:

```
The following signatures were invalid: EXPKEYSIG 83F79AD029778355 Wiretrustee <dev@wiretrustee.com>
```

UPD: Actually, both deb and rpm keys have expired:

```
> curl -s https://pkgs.wiretrustee.com/debian/public.key | gpg --show-keys -
pub   rsa3072 2021-09-25 [SC] [expired: 2023-09-25]
      EFE37DF047DF7CCDF1FC54FA83F79AD029778355
uid                      Wiretrustee <dev@wiretrustee.com>
sub   rsa3072 2021-09-25 [E] [expired: 2023-09-25]
```

```
> curl -s https://pkgs.netbird.io/yum/repodata/repomd.xml.key | gpg --show-keys -
pub   rsa3072 2021-09-25 [SC] [expired: 2023-09-25]
      AA9C09AA9DEA2F58112B40DFDFFEAB2FD267A61F
uid                      Wiretrustee <dev@wiretrustee.com>
sub   rsa3072 2021-09-25 [E] [expired: 2023-09-25]
```

**Comment by mlsmaycon** [comment]
Thank you, @shvchk the keys have been updated on our package repositories and in this repository.

**Comment by shvchk** [comment]
@mlsmaycon deb key `https://pkgs.wiretrustee.com/debian/public.key` is still expired:

```
> curl -s https://pkgs.wiretrustee.com/debian/public.key | gpg --show-keys -
pub   rsa3072 2021-09-25 [SC]
      EFE37DF047DF7CCDF1FC54FA83F79AD029778355
uid                      Wiretrustee <dev@wiretrustee.com>
sub   rsa3072 2021-09-25 [E] [expired: 2023-09-25]
```

**Comment by mlsmaycon** [comment]
Hello @shvchk I've uploaded the correct key, can you validate again?

**Comment by shvchk** [comment]
Yep, it's fine now, thanks.

There's a discrepancy in docs / installation methods though, which might confuse users updating the key:

- [Installation docs](https://docs.netbird.io/how-to/installation):
  - Key source: https://pkgs.netbird.io/debian/public.key
  - Key location: `/usr/share/keyrings/netbird-archive-keyring.gpg`
  - Repo source file: `/etc/apt/sources.list.d/netbird.list`
- Control panel _Add peer_ guide:
  - Key source: https://pkgs.wiretrustee.com/debian/public.key
  - Key location: `/etc/apt/trusted.gpg.d/wiretrustee.gpg`
  - Repo source file: `/etc/apt/sources.list.d/wiretrustee.list`
- [Installation script](https://pkgs.netbird.io/install.sh):
  - Key source: https://pkgs.wiretrustee.com/debian/public.key
  - Key location: `/usr/share/keyrings/wiretrustee-archive-keyring.gpg`
  - Repo source file: `/etc/apt/sources.list.d/wiretrustee.list`

So there's 3 different possible key locations and 2 repo source file locations, and when user uses one official way to install netbird, and then another official way to update the key, they will end up with an old key in one of the locations, and `apt` will refuse to use the repo.

It would be better to pick one key and repo source file location and use it in all official docs / installation methods.

For now, the proper way to update the key on Debian / Ubuntu is to remove all old keys and repo sources and then readd:

```sh
sudo rm -f \
  /etc/apt/sources.list.d/netbird.list \
  /etc/apt/sources.list.d/wiretrustee.list \
  /etc/apt/trusted.gpg.d/wiretrustee.gpg \
  /usr/share/keyrings/netbird-archive-keyring.gpg \
  /usr/share/keyrings/wiretrustee-archive-keyring.gpg

curl -sSL https://pkgs.netbird.io/debian/public.key \
| sudo gpg --dearmor -o /usr/share/keyrings/netbird-archive-keyring.gpg

echo 'deb [signed-by=/usr/share/keyrings/netbird-archive-keyring.gpg] https://pkgs.netbird.io/debian stable main' \
| sudo tee /etc/apt/sources.list.d/netbird.list

sudo apt update
```

**Comment by shvchk** [comment]
Looks like keys are now ok, and all docs and scripts are in sync. Thanks, closing : )
